"""add new fields in student table

Revision ID: 2f7b1cca9fb0
Revises: f122675a49c8
Create Date: 2026-03-09 09:10:55.699109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7b1cca9fb0'
down_revision = 'f122675a49c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stu_gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stu_course', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stu_library_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stu_join_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('stu_address', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['stu_library_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stu_address')
        batch_op.drop_column('stu_join_date')
        batch_op.drop_column('stu_library_id')
        batch_op.drop_column('stu_course')
        batch_op.drop_column('stu_gender')

    # ### end Alembic commands ###
