"""empty message

Revision ID: 57f6e77cd7aa
Revises: 2f7b1cca9fb0
Create Date: 2026-03-09 16:16:41.478570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f6e77cd7aa'
down_revision = '2f7b1cca9fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_name', sa.String(length=100), nullable=False),
    sa.Column('auth_email', sa.String(length=100), nullable=True),
    sa.Column('auth_phone', sa.String(length=10), nullable=False),
    sa.Column('auth_country', sa.String(length=50), nullable=False),
    sa.Column('auth_bio', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_email'),
    sa.UniqueConstraint('auth_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
