"""student table 

Revision ID: f122675a49c8
Revises: 
Create Date: 2026-03-06 10:49:57.627886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f122675a49c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stu_name', sa.String(length=100), nullable=False),
    sa.Column('stu_age', sa.Integer(), nullable=False),
    sa.Column('stu_email', sa.String(length=100), nullable=True),
    sa.Column('stu_phone', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stu_email'),
    sa.UniqueConstraint('stu_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
